// IPC 通道名集中定义，避免两端写错字符串。
export const CH = {
  appInfo: 'app:info',
  configGet: 'config:get',
  configSet: 'config:set',
  libraryStats: 'library:stats',
  libraryCandidates: 'library:candidates',
  /** 多数据目录 */
  librariesList: 'libraries:list',
  libraryCreate: 'libraries:create',
  libraryActivate: 'libraries:activate',
  libraryRename: 'libraries:rename',
  libraryRemove: 'libraries:remove',
  libraryPickFolder: 'libraries:pick-folder',
  /** 云数据目录 */
  cloudConnect: 'cloud:connect',
  cloudConnectKey: 'cloud:connect-key',
  cloudTestKey: 'cloud:test-key',
  cloudStatus2: 'cloud:status2',
  cloudUpload2: 'cloud:upload2',
  cloudDownload2: 'cloud:download2',
  cloudRestore2: 'cloud:restore2',
  cloudDevices2: 'cloud:devices2',
  cloudRemoveDevice: 'cloud:remove-device',
  /** 复制文本到系统剪贴板（走主进程，避免渲染层权限/焦点问题） */
  copyText: 'app:copy-text',
  /** 取拖进来文件的绝对路径（webUtils） */
  filePath: 'app:file-path',
  /** 断开云数据目录：注销本机登记 + 从列表移除 */
  cloudDisconnect: 'cloud:disconnect',
  cloudLeave: 'cloud:leave',
  libraryTargets: 'libraries:copy-targets',
  libraryCopy: 'libraries:copy',
  librarySaveAsLocal: 'libraries:save-as-local',
  cloudStatus: 'cloud:status',
  cloudUpload: 'cloud:upload',
  cloudDownload: 'cloud:download',
  cloudRestoreBackup: 'cloud:restore-backup',
  librarySwitch: 'library:switch',

  taskList: 'task:list',
  taskCreate: 'task:create',
  taskUpdate: 'task:update',
  taskComplete: 'task:complete',
  taskDelete: 'task:delete',
  tagList: 'tag:list',
  tagCreate: 'tag:create',
  tagRename: 'tag:rename',
  tagDelete: 'tag:delete',
  tagMove: 'tag:move',
  trashTaskList: 'trashTask:list',
  trashTaskRestore: 'trashTask:restore',
  trashTaskPurge: 'trashTask:purge',
  historyList: 'history:list',

  noteTree: 'note:tree',
  noteRead: 'note:read',
  noteSave: 'note:save',
  noteForceSave: 'note:force-save',
  noteBackup: 'note:backup-draft',
  /** 打开一个链接或本地文件/文件夹（网页走浏览器，本地走系统默认程序） */
  openTarget: 'shell:open-target',
  /** 弹出系统文件选择框，返回绝对路径 */
  pickFile: 'dialog:pick-file',
  noteCreate: 'note:create',
  noteRename: 'note:rename',
  noteMove: 'note:move',
  noteDelete: 'note:delete',
  folderCreate: 'folder:create',
  folderRename: 'folder:rename',
  folderMove: 'folder:move',
  folderDelete: 'folder:delete',
  noteRestoreOrigin: 'note:restoreOrigin',
  trashNoteList: 'trashNote:list',
  trashNoteRestore: 'trashNote:restore',
  trashNotePurge: 'trashNote:purge',
  attachmentImport: 'attachment:import',
  /** 把剪贴板/拖拽进来的图片数据存成附件 */
  attachmentFromData: 'attachment:from-data',
  attachmentUrl: 'attachment:url',
  attachmentData: 'attachment:data',
  /** DSH 版新增：只查不删，列出"没有任何笔记/白板引用"的附件（彻底删除前做知情确认用） */
  attachmentOrphans: 'attachment:orphans',
  /** DSH 版新增：文档保真读取（PDF 逐页渲染成图 + Office/文本抽取） */
  docRead: 'doc:read',

  boardRead: 'board:read',
  boardSave: 'board:save',

  revealPath: 'shell:reveal',
  openExternal: 'shell:openExternal',

  aiStatus: 'ai:status',
  aiSetKey: 'ai:setKey',
  aiClearKey: 'ai:clearKey',
  aiConverseList: 'ai:converseList',
  aiPendingList: 'ai:pendingList',
  aiSend: 'ai:send',
  aiConfirm: 'ai:confirm',
  aiCancel: 'ai:cancel',
  aiStop: 'ai:stop',
  aiUndo: 'ai:undo',
  aiSteps: 'ai:steps',
  aiDangerAnswer: 'ai:danger-answer',
  aiEngineGet: 'ai:engine-get',
  aiEngineSet: 'ai:engine-set',
  aiPickFiles: 'ai:pickFiles',
  aiApplyNoteEdits: 'ai:applyNoteEdits',
  aiAbort: 'ai:abort'
} as const
